parameters:
#    afpa_color.example.class: Afpa\ColorBundle\Example

services:
#    afpa_color.example:
#        class: %afpa_color.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
