parameters:
#    afpa_calculette.example.class: Afpa\CalculetteBundle\Example

services:
#    afpa_calculette.example:
#        class: %afpa_calculette.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
